### ISSUE TITLE
Crash when incorrectly calling member function

### ISSUE THREAD

**Issue by Flamefire** [satoren/kaguya#15]
I found a crash that can easily occur by a typo in the lua code:

    std::map<unsigned, unsigned> myMap;

    class FooClass{
    public:
        void mapCallback(const std::map<unsigned, unsigned>& map)
        {
            myMap = map;
        }
    };

    void testMap(kaguya::State& state)
    {
        state["testMap"].setClass(kaguya::ClassMetatable<FooClass>().addMemberFunction("testMap", &FooClass::mapCallback));
        state["foo"] = FooClass();
        // Wrong -> Crash
        state("myMap = {[1]=2, [3]=4, [5]=6}\n foo.testMap(myMap)");
        //Correct
        state("myMap = {[1]=2, [3]=4, [5]=6}\n foo:testMap(myMap)");
        TEST_EQUAL(myMap[1], 2);
        TEST_EQUAL(myMap[3], 4);
        TEST_EQUAL(myMap[5], 6);
    }

The reason is that the `.` instead of `:` skips the `this` pointer and kaguya does not detect the invalid argument count and happily tries to get a map from index 2 at the stack which is not there. Such errors should be detected

**Comment by satoren** [comment]
thanks for report and PR.
It fixed code did not use, but merged test code.
