### ISSUE TITLE
Throw error on invalid return values

### ISSUE THREAD

**Issue by Flamefire** [satoren/kaguya#19]
I have code like this:

    std::vector<unsigned> GetValues()
    {
        kaguya::LuaRef getValues= lua["getValues"];
        if(getValues.type() == LUA_TFUNCTION)
            return getValues();
        return std::vector<unsigned>();
    }

And I want this code to throw an error or something so I can detect when the lua function returns invalid types. E.g. in this case the lua function returned a table of strings instead of numbers.

Problem is: I just get the empty vector and have no way to tell if the vector was actually empty or just had some wrong elements.

**Comment by satoren** [comment]
use typeTest or weakTypeTest.
If you want to distinguish between the string and the number, use typeTest.

```C++
std::vector<unsigned> GetValues()
{
    kaguya::LuaRef getValues= lua["getValues"];
    if(getValues.type() == LUA_TFUNCTION)
   {
     kaguya::LuaRef array =  getValues();
    if(array.typeTest<std::vector<unsigned> >())
    {
      return array;//valid
    }     
    else
    {
        throw std::runtime_error("invalid array");
     }
   }
    return std::vector<unsigned>();
}
```

If you want type check at per elements.
```C++
std::vector<unsigned> result;
 std::vector<kaguya::LuaRef> array =  getValues();
for(auto& elem : array)
{
    if(elem.typeTest<unsigned>())
    {
       result.push_back(elem);
    }
    else
    {
        //invalid
   }
}
return result;
```

**Comment by Flamefire** [comment]
This is what I ended up with. However this is quite some boilerplate code (even the check, if it is a function) and I was hoping that there is some library support. E.g. `getValues.call<std::vector<unsigned> >()` could result in a lua error if the type is wrong.
Also doing the check this way does it twice: Once for checking and once before it is converted. Maybe something like `getValues().assertConvertible()` and/or `getValues().checkConvertible(bool& wasValid)`?

**Comment by satoren** [comment]
like this?
```C++
  bool typevalid;
  auto result = getValues().get<std::vector<unsigned> >(typevalid, false);
  if(typevalid)
  {
    return result;//valid
  }
  else
  {
    return std::vector<unsigned>();
  }
```

**Comment by Flamefire** [comment]
Yes, pretty nice solution.

Does this really work? because `getValues()` returns `FunctionResults` for which you did not implement this get function or did I miss anything? Also the code needs to be duplicated in LuaRef, LuaTableRef and FuntionResults. maybe you can improve that (just style/maintainability issue though)

Lastly: What about performance? Type checking is done twice. Could you check the performance of the type check for getting a vector of some (~100?) ints that need to be converted from string (kind of bad, but still reasonable case)?

**Comment by satoren** [comment]
type checking is done once for element since 4a6f5abf28fe1b0a95489b141496a7d7f90cdb97
table type check is twice for avoid panic.

**Comment by satoren** [comment]
Example of the type checking of performance cost.
bool was_valid;
`std::vector<double> r = lua_table.get<std::vector<double>>(was_valid);`

| lua api  | call count  | reason |
|:-----------|------------:|:------------:|
|lua_type() |   2 | table type check|
|lua_next() | table element count * 2 |element loop for type check and get value |
|lua_pop() | table element count * 2 |element loop|
|lua_isinteger()  | table element count |type check for key|
|lua_tonumber()  | table element count |get value |
|lua_isnumber()  | table element count |type check for value|
|lua_gettop| many | |
|lua_settop| many | |

**Comment by Flamefire** [comment]
Looks quite good. I still think, that this can be improved by combining the type check and get value parts completely. So it actually gets the values but optionally sets the `was_valid` variable to false as it iterates over the table. This would save the factor 2 in the call count and some instantiations for example of `LuaStackRef`
But well, do you already have benchmark results for the call with `was_valid` vs without?

**Comment by satoren** [comment]
kaguya_api_benchmark______::table_to_vector min time:0.076
kaguya_api_benchmark______::table_to_vector_with_typecheck min time:0.208

**Comment by Flamefire** [comment]
Ouch... Almost 3 times slower :/
I can try to come up with something to make it faster, if you like

**Comment by satoren** [comment]
Please try it.
