### ISSUE TITLE
Error adding metatable to member std::vector

### ISSUE THREAD

**Issue by Unril** [satoren/kaguya#2]
Example test code:

```c++
using TestVect  = vector<int>;

int getItem(TestVect &v, int i) { return v.at(i); }

struct TestStrcutWithVect {
    TestVect vect;
};

TEST(Add_metatable_to_member_vector) {
    kaguya::State s;
    s["Vect"].setClass(kaguya::ClassMetatable<TestVect>().addStaticMember("getItem", getItem));
    s["TestStrcutWithVect"].setClass(kaguya::ClassMetatable<TestStrcutWithVect>().addProperty(
        "vect", &TestStrcutWithVect::vect));

    TestStrcutWithVect test;
    test.vect.push_back(123);
    s["test"] = &test;
    s("i = test.vect:getItem(0)");

    EXPECT_THAT(s["i"], Eq(123));
}
```
Gives: `[string "i = test.vect:getItem(0)"]:1: attempt to call method 'getItem' (a nil value)
unknown file: error: C++ exception with description "nilis not __int64" thrown in the test body.`

Following test also fails:
```c++
TEST(Pass_member_vector_to_free_function) {
    kaguya::State s;
   s["Vect"].setClass(kaguya::ClassMetatable<TestVect>());
    s["TestStrcutWithVect"].setClass(kaguya::ClassMetatable<TestStrcutWithVect>().addProperty(
        "vect", &TestStrcutWithVect::vect));
	s["getItem"] = getItem;

    TestStrcutWithVect test;
    test.vect.push_back(123);
    s["test"] = &test;
    s("i = getItem(test.vect, 0)");

    EXPECT_THAT(s["i"], Eq(123));
}
```
With message `argument not matching:table,number	 candidated
		class std::vector<int,class std::allocator<int> >,int
unknown file: error: C++ exception with description "nilis not __int64" thrown in the test body.`

Same story with `using TestVect  = string;`. But if I replace `using TestVect  = vector<int>;` to `struct TestVect  : vector<int>{};` or `using TestVect  = array<int, 10>;` all tests pass.

If vector isn't a member then metatable is added and followig test passes:

```c++
using TestVect  = vector<int>;

TEST(Add_metatable_to_vector) {
    kaguya::State s;
    s["Vect"].setClass(kaguya::ClassMetatable<TestVect>().addStaticMember("getItem", getItem));

    TestVect vect;
    vect.push_back(123);
    s["vect"] = &vect;
    s("i = vect:getItem(0)");

    EXPECT_THAT(s["i"], Eq(123));
}
```

**Comment by satoren** [comment]
I'm sorry, it is undocumented.
std::vector (and std::map) binding is specialized to table.

```C++
kaguya::State s;
std::vector<int> vect = { 2,4,6,1 };
s["vect"] = vect;
s("print(type(vect))");// table
s("for i,v in ipairs(vect) do print(v) end");
```
output:
table
2
4
6
1

**Comment by Unril** [comment]
But how to deal with cases like this one (suppose it's not a simple indexing):
```c++
int getItem(TestVect &v, int i) { return v.at(i); }
...
s("i = getItem(test.vect, 0)");
```

**Comment by satoren** [comment]
maybe you wants this?
```C++
int getItem(const std::vector<int> &t, int i) { return t.at(i); }

kaguya::State s;
std::vector<int> vect = { 2,4,6,1 };
s["getItem"] = &getItem;
s["test"]=kaguya::NewTable();
s["test"]["vect"] = vect;

s("i = getItem(test.vect, 0)");
```

**Comment by Unril** [comment]
Use case, for example:
```c++
struct Point { float x, y; };

using Points = vector<Point>;

void normalizePoints(Points &pts) { 
    for(auto &p: pts) { normalizePoint(p); }
}

struct Mesh { Points normals; };
```
In lua:
```lua
mesh = Mesh.new()
normalizePoints(mesh.normals)
```

**Comment by satoren** [comment]
I understand what you want.
it is non-const reference of vector<Point> of std::vector in arguments.
but its problem is difficult.


this code is not recommended.because the test is not enough
```c++
namespace kaguya{ namespace traits{
		template<>struct is_push_specialized<Points> : integral_constant<bool, false> {};//disable std::vector to lua-table mapping
}}

kaguya::State s;
s["Points"].setClass(kaguya::ClassMetatable<Points>());
s["Mesh"].setClass(kaguya::ClassMetatable<Mesh>()
	.addConstructor()
	.addProperty("normals", &Mesh::normals));
s["normalizePoints"] = &normalizePoints;
s("mesh = Mesh.new()");
s("normalizePoints(mesh.normals)");
```
or wrap normalizePoints(exist copy cost)
```c++
kaguya::State s;
s["Point"].setClass(kaguya::ClassMetatable<Point>());
s["Mesh"].setClass(kaguya::ClassMetatable<Mesh>()
	.addConstructor()
	.addProperty("normals", &Mesh::normals));
	
s["normalizePoints"] = kaguya::function([](Points copy)
{
	normalizePoints(copy);
	return copy;
});
s("mesh = Mesh.new()");
s("mesh.normals = normalizePoints(mesh.normals)");
```
or 
`struct Points: vector<Point>{};`


std::string case.
I think many users hope std::string to lua-string.
but lua-string is nonmutable. because cant convert to non-const reference.
better way is wrap of function

**Comment by Unril** [comment]
But working with vector added to global table doesn't have this issue. Maybe it's better to make working with properties consistent with it? Or there are some hidden problems with this approach?

**Comment by satoren** [comment]
ok. add KAGUYA_NO_VECTOR_AND_MAP_TO_TABLE.
defailt is 0
bcde5058dcca3323e69936dc534c485e65c4b27e

**Comment by Unril** [comment]
Thanks. Now it makes sense. I hope it will be highlighted in documentation soon.

**Comment by satoren** [comment]
compile error on ClassMetatable<std::vector<type> >();
and error message `std::vector is binding to lua-table by default.If you wants register for std::vector yourself,please define KAGUYA_NO_STD_VECTOR_TO_TABLE`
