### ISSUE TITLE
Call member function is slow than property.

### ISSUE THREAD

**Issue by aster2013** [satoren/kaguya#32]
Call member function is slow than property.

with ```sprite:GetPosition, sprite:SetPosition``` get fps 54
with ```sprite.position``` get fps 125

**Comment by satoren** [comment]
I’m sorry. Can you define KAGUYA_RETURN_VALUE_OPTIMIZATION 0 or change in kaguya/config.hpp ?
If faster change. i remove it.

**Comment by aster2013** [comment]
#define KAGUYA_RETURN_VALUE_OPTIMIZATION  0 will faster than 1.
but the function call remain slow than property call.

**Comment by satoren** [comment]
OK. When I get home,will check it.

**Comment by aster2013** [comment]
Bug. This function not push v to Lua.

```
namespace nativefunction
	{
#if KAGUYA_RETURN_VALUE_OPTIMIZATION
		template<typename T>
		struct is_return_reference_optimize :traits::integral_constant<bool,
			is_usertype<typename traits::decay<T>::type>::value	&&
			(traits::is_pointer<T>::value	||
			traits::is_lvalue_reference<T>::value)>{};

		template<typename T>
		inline int optimized_push_return_value(lua_State* state,T* v)
		{
			int top = lua_gettop(state);
			for (int i = 1; i <= top; ++i)
			{
				if (lua_type_traits<T*>::get(state, i))
				{
					lua_pushvalue(state, i);
					return 1;
				}
			}
			return util::push_args(state, v);
		};
```

**Comment by satoren** [comment]
Not bug (but slow). If argument and return value(v) is same, push stack value`lua_pushvalue(state, i);`  , It is no newuserdata(not heap allocation).

**Comment by aster2013** [comment]
I known what your mean. but only check argument type not argument value. eg.
```
Node* Node::CreateChild(const char* name);
```
will not push the return value to stack.

**Comment by satoren** [comment]
Omg! you are right.

**Comment by satoren** [comment]
Forgot `==v` ,  but already remove that.

**Comment by aster2013** [comment]
Thanks. By the way, Where are you?

**Comment by satoren** [comment]
at home now.

**Comment by aster2013** [comment]
USA?

**Comment by satoren** [comment]
No. it's seacret.

**Comment by aster2013** [comment]
Sorry. Kaguya is cool.  If you have time, I want to invite you work on Urho3D.

**Comment by satoren** [comment]
Thanks.
