### ISSUE TITLE
registering function not working

### ISSUE THREAD

**Issue by Memorix101** [satoren/kaguya#36]
Hey :)

I can't call the C++ function in Lua I just registered :(

```
void print_text(const char* msg)
{
	//printf("%s", msg.c_str());
	std::cout << "kaguya rocks ! " << msg << std::endl;
}
	
kaguya::State state;
kaguya::LoadLibs();
state.dofile("test.lua");

state["print_text"] = &print_text;

```
I always get "test.lua:7: attempt to call a nil value (global 'print_text')"

but calling `state["print_text"]("meep");` works :P

In my lua script it's just `print_text("hello world\n)`

**Comment by satoren** [comment]
Are you running test.lua  before register a function?
```
void print_text(const char* msg)
{
    //printf("%s", msg.c_str());
    std::cout << "kaguya rocks ! " << msg << std::endl;
}

kaguya::State state;
state["print_text"] = &print_text;
state.dofile("test.lua");

```

**Comment by Memorix101** [comment]
Ahhh, that's it.  
Sure, then it can't work.

Thank you ^-^

**Comment by satoren** [comment]
Your welcome.
