### ISSUE TITLE
A few questions about functions

### ISSUE THREAD

**Issue by Memorix101** [satoren/kaguya#37]
Hey I wanted to ask a few questions ...

When I try to call a lua function from my test lua script the application crashes, but the examples works
without any issue, same for getting a variable from my script. 
`int ret = state["math"]["abs"](-32);`  works 
but
```
function getvalue(x)
return x
end
```

`int ret = state["getvalue"](5);` 
doesn't :(

well ...
```
        state("multresfun =function() return 1,2,4 end");//registering multiple results function
    int a, b, c;
        kaguya::tie(a, b, c) = state["multresfun"]();
```
works, but he same called from lua file doesn't :(
So, do I do something wrong or forgot something ?!

My next question is how can I register a function in C++ and call it like

```
function mycppfunction
 bla bla bla
end
```

That's it so far.
Your lua binding is awesome :) I love it ! :D
Shiny and clean :D :+1: 

Thanks :)

**Comment by satoren** [comment]
Work this.
```
kaguya::State state;
state("function getvalue(x) return x end");
int ret = state["getvalue"](5);
assert(5 == ret);
```
Can you read errror message? 
Default is output to stderr. It can customize by State::setErrorHandler.


Youre code.
```
function mycppfunction
 bla bla bla
end
```
Sytax error? 
If you want multiple return value from C++, use tuple.
```
std::tuple<std::string,std::string,std::string> multiple_return()
{
  return std::tuple<std::string,std::string,std::string>("bla1","bla2","bla3");
}

state["multiple_return"] = &multiple_return;
state("print(multiple_return())");//bla1   bla2     bla3
```
If you use C++03 std::tuple change to boost::tuple or kaguya::standard::tuple.

**Comment by Memorix101** [comment]
![eeeee](https://cloud.githubusercontent.com/assets/1466920/16843533/dca3b426-49e1-11e6-8da8-22acb2a41c07.PNG)

You seem to misunderstand my second question.

I want to register a function to be called in Lua.
In stead of normal function call `myfunction`  in syntax. 
I want:

```
function mycppfunction
 bla bla bla
end
```

For example, I register a function called OnUpdate in C++.
Then I call it in Lua:
```
function OnUpdate()
--code in here will be called as endless loop to my main.cpp
end
```

**Comment by satoren** [comment]
Hmm. I don't understand.
``` C++
kaguya::State state;
state.dofile("file.lua");//function OnUpdate()   end in file.lua
kaguya::LuaFunction OnUpdate = state["OnUpdate"];//get OnUpdate function from lua
while(exit)//event loop
{
  // process input
   OnUpdate();//call Lua update
  //render to screen
}
```
This kind of thing?

**Comment by Memorix101** [comment]
yup, exactly :)

**Comment by satoren** [comment]
kaguya::LuaFunction is can wrap by std::function.

1.  ```kaguya::LuaFunction OnUpdate = state["OnUpdate"];```
2. ```std::function<void()> OnUpdate = state["OnUpdate"];```

1 is just a little better performance.

**Comment by Memorix101** [comment]
Ok, do I need to place `kaguya::LuaFunction OnUpdate = state["OnUpdate"];` just inside my while or do I need to register it first somehow ?

I tried to place it inside my main loop and it crashes ... 
I tried this:

Lua:
```
function  OnUpdate()
  --draw("data/nalacat.jpg")
  print_text("hi")
end
```

C++:

```
while(true)
{
kaguya::LuaFunction OnUpdate = state["OnUpdate"];
}
```

**Comment by satoren** [comment]
Did you solve?

**Comment by Memorix101** [comment]
Yes :)
Thank you :D

**Comment by satoren** [comment]
Your welcome.
