### ISSUE TITLE
New feature request.

### ISSUE THREAD

**Issue by aster2013** [satoren/kaguya#40]
Hi, Satoren, your kaguya is greater, now the Urho3D Lua API with kaguya is finished.  thanks. 

These is a class call ```StringHash``` in Urho3D, I have bind it to Lua as a user data. When I call some functions with StringHash arguments, I can do like this:
```
// C++
void SomeFunction(StringHash hash);

// Lua
SomeFunction(StringHash('This is a string'))
```
But sometimes I want to call like this:
```
// Lua
SomeFunction('This is a string')
```
Now I can not write a ``` lua_type_traits<StringHash>``` specialization class, because kaguya forbid it.

**Comment by satoren** [comment]
Congratulations for finished!

Forbid  reason is cause of mistakes..
But at least can it.　I do not recommend...

Registerable member define in lua_type_traits.
e.g.
```
template<>struct lua_type_traits<StringHash>
{
  typedef void Registerable;//define "Registerable" member. Then will be able to register.
  typedef StringHash gett_ype;
  static bool checkType(lua_State* l, int index)
  {
    //allow StringHash or string type
    return object_wrapper<StringHash>(l, index) != 0 ||  lua_type_traits<std::string>::checkType(l,index);
  }
  static bool strictCheckType(lua_State* l, int index)
  {
    //allow StringHash or string type
    return object_wrapper<StringHash>(l, index,false) != 0 ||  lua_type_traits<std::string>::strictCheckType(l,index);
  }

  get_type get(lua_State* l, int index)
  {
    const char* str = lua_tostring(l,index);
    if(str){return StringHash(str);}
 
    const StringHash* pointer = get_const_pointer(l, index, types::typetag<StringHash>());
    if (pointer)
    {
      return *pointer;
    }
    throw LuaTypeMismatch("type mismatch!!");
  }
};
```
This is better performance. But very troublesome.
I am considering something like can register the type conversion function.

**Comment by aster2013** [comment]
Thanks.
