### ISSUE TITLE
crash with Xcode Version 8.2.1 (8C1002)

### ISSUE THREAD

**Issue by yinjimmy** [satoren/kaguya#58]
```
        kaguya::State state;
        state["a"] = "test";
```

![image](https://cloud.githubusercontent.com/assets/5056328/24088483/dcbb6b32-0d65-11e7-8030-28766024fef0.png)

**Comment by satoren** [comment]
std::__1::__hash_table is internal implement for unordered_set/map.
kaguya not use unordered_set/map.
