### ISSUE TITLE
Build error on macOS Sierra

### ISSUE THREAD

**Issue by Arthapz** [satoren/kaguya#59]
Hi,
Kaguya don't work on macOS

`/include/kaguya/object.hpp:86:11: error: no viable conversion from returned value of type
      '__bit_iterator<std::__1::vector<bool, std::__1::allocator<bool> >, true>' to function return type 'const void *'
                        return &object_;
                               ^~~~~~~~
/Users/arthapz/Downloads/ObEngine-master/extlibs/include/kaguya/object.hpp:63:3: note: in instantiation of member function
      'kaguya::ObjectWrapper<std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > >::cget' requested here
                ObjectWrapper(Args&&... args) : object_(std::forward<Args>(args)...) {}
                ^
/Users/arthapz/Downloads/ObEngine-master/extlibs/include/kaguya/object.hpp:732:17: note: in instantiation of function template specialization
      'kaguya::ObjectWrapper<std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >
      >::ObjectWrapper<std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > >' requested here
                        new(storage) wrapper_type(std::forward<T>(v));
                                     ^
/Users/arthapz/Downloads/ObEngine-master/extlibs/include/kaguya/type.hpp:66:16: note: in instantiation of function template specialization
      'kaguya::util::object_push<std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > >' requested here
                return util::object_push(l,std::forward<NCRT>(v));
                             ^
/Users/arthapz/Downloads/ObEngine-master/extlibs/include/kaguya/utility.hpp:200:64: note: in instantiation of member function
      'kaguya::lua_type_traits<std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >, void>::push' requested here
                        int c = lua_type_traits<typename traits::decay<Arg>::type>::push(l, std::forward<Arg>(arg));
                                                                                    ^
/Users/arthapz/Downloads/ObEngine-master/extlibs/include/kaguya/utility.hpp:233:22: note: in instantiation of function template specialization
      'kaguya::util::push_args<std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >>' requested here
                        int count = util::push_args(state, std::forward<T>(v));
                                          ^
/Users/arthapz/Downloads/ObEngine-master/extlibs/include/kaguya/lua_ref_table.hpp:497:11: note: (skipping 1 context in backtrace; use -ftemplate-backtrace-limit=0
      to see all)
                                util::one_push(l, *it);
                                      ^
/Users/arthapz/Downloads/ObEngine-master/extlibs/include/kaguya/utility.hpp:200:64: note: in instantiation of member function
      'kaguya::lua_type_traits<std::__1::vector<bool, std::__1::allocator<bool> >, void>::push' requested here
                        int c = lua_type_traits<typename traits::decay<Arg>::type>::push(l, std::forward<Arg>(arg));
                                                                                    ^
/Users/arthapz/Downloads/ObEngine-master/extlibs/include/kaguya/utility.hpp:233:22: note: in instantiation of function template specialization
      'kaguya::util::push_args<std::__1::vector<bool, std::__1::allocator<bool> > &>' requested here
                        int count = util::push_args(state, std::forward<T>(v));
                                          ^
/Users/arthapz/Downloads/ObEngine-master/extlibs/include/kaguya/detail/lua_table_def.hpp:37:11: note: in instantiation of function template specialization
      'kaguya::util::one_push<std::__1::vector<bool, std::__1::allocator<bool> > &>' requested here
                                util::one_push(state, std::forward<V>(value));
                                      ^
/Users/arthapz/Downloads/ObEngine-master/extlibs/include/kaguya/lua_ref_table.hpp:58:25: note: in instantiation of function template specialization
      'kaguya::detail::table_proxy::set<std::__1::vector<bool, std::__1::allocator<bool> > &, std::__1::basic_string<char> &>' requested here
                        detail::table_proxy::set(state_, table_index_, key_, std::forward<T>(src));
                                             ^
/Users/arthapz/Downloads/ObEngine-master/src/GameObject.cpp:296:51: note: in instantiation of function template specialization
      'kaguya::TableKeyReferenceProxy<std::__1::basic_string<char> >::operator=<std::__1::vector<bool, std::__1::allocator<bool> > &>' requested here
                                                                (*m_objectScript)["cpp_param"][it->first] = allParam->at(it->first).second.as<std::vector<bool>>();`

**Comment by satoren** [comment]
Thank you for report

**Comment by Arthapz** [comment]
There is always some errors
https://pastebin.com/gn649C0X

**Comment by satoren** [comment]
Can you update kaguya? look like line number is old version

**Comment by Arthapz** [comment]
with updated kaguya https://pastebin.com/Jx8kbkLv

**Comment by satoren** [comment]
I'm sorry,  missed merge in 9c25fa21b7b891a150eb076bb2a6d5df618cb8fe
