### ISSUE TITLE
how to use in multi so or dll

### ISSUE THREAD

**Issue by owen200008** [satoren/kaguya#62]
a.so export  class A
lua require b.so have interface param 1 is A
how to get a point if use kaguya::get_pointer(L, nIndex, kaguya::types::typetag<T>());
the metatable_name_key is not same so it will fail

**Comment by owen200008** [comment]
so i suggest metatable_name_key and metatable_type_table_key use fix address

**Comment by satoren** [comment]
Thank you for the report.

**Comment by owen200008** [comment]
when use kaguya::get_pointer(L, nIndex, kaguya::types::typetag<T>());
the type_info compare is not same。so get the object is nullptr
how to solve?
