### ISSUE TITLE
lua_rawget_rtype is not define in lua5.1

### ISSUE THREAD

**Issue by owen200008** [satoren/kaguya#63]
lua_rawget_rtype is not define in lua5.1

**Comment by satoren** [comment]
what verion of kaguya?

**Comment by owen200008** [comment]
just clone 15day ago。it is the newest。

**Comment by satoren** [comment]
https://github.com/satoren/kaguya/blob/master/include/kaguya/compatibility.hpp#L119

lua_rawget_rtype  implemented in `#if LUA_VERSION_NUM < 503`
