### ISSUE TITLE
Passing a LuaRef from a kaguya::State to another kaguya::State

### ISSUE THREAD

**Issue by Sygmei** [satoren/kaguya#66]
How to pass a value from one state to another ? Using kaguya::LuaRef doesn't work, is there another way ?

```cpp
kaguya::State luaP;
kaguya::State luaQ;
luaP("test = \"hello\"");
kaguya::LuaRef retainValue = luaP["test"];
luaQ["test"] = test;
luaQ("print(test)");
```
Doing it like that works but I want to store a kaguya::LuaRef or something like that

```
kaguya::State luaP;
kaguya::State luaQ;
luaP("test = \"hello\"");
luaQ["test"] = luaP["test"];
luaQ("print(test)");
```

**Comment by Sygmei** [comment]
Nevermind, my mistake !

**Comment by Sygmei** [comment]
I get the following error : 
```
Assertion failed: util::toMainThread(state) == util::toMainThread(ref_.state()), file lua_ref_impl.hpp, line 297
```

**Comment by satoren** [comment]
Normally you can not. but you can try serialization. 

https://www.lua.org/pil/12.1.html
http://lua-users.org/wiki/TableSerialization

Remember that some type can not be serialized.(e.g function)

**Comment by Sygmei** [comment]
Then why passing from one LuaState to another works ?

```cpp
luaP["something"] = luaQ["somethingelse"];
```

**Comment by satoren** [comment]
Lua has not that feature.

**Comment by Sygmei** [comment]
Okay, thanks :) 
Good job for your lib by the way, it's really comfortable to use
