### ISSUE TITLE
Performance while function call

### ISSUE THREAD

**Issue by Unril** [satoren/kaguya#7]
In genrated code like
```c++
template<typename T1>
inline FunEvaluator LuaRef::operator()(T1 t1)
{
  value_type typ = type();
  if(typ != TYPE_FUNCTION && typ != TYPE_THREAD){except::typeMismatchError(state_, "is not function");return FunEvaluator(state_);}
  int argstart = lua_gettop(state_);
  lua_type_traits<T1>::push(state_,standard::forward<T1>(t1));
  int argnum = lua_gettop(state_) - argstart;
  std::vector<LuaRef> args;
  args.reserve(argnum);
  for (int i = 0; i < argnum; ++i)
    args.push_back(LuaRef(state_, StackTop()));
  std::reverse(args.begin(), args.end());
  return FunEvaluator(state_,*this,args);
}
```
change last line to `return FunEvaluator(state_,*this, std::move(args));`. It prevents vector copying and gives non-negligible perf increase while func calling. May be there are other places where such optimization can be made.

**Comment by satoren** [comment]
changed to simple, and performance upped.
call function benchmark 0.745 to 0.282 on my environment

**Comment by satoren** [comment]
move effect is limited because most are optimized by RVO

if you need high performance, you can use "call".
this is high performance. but not automaticaly type conversion for return

https://github.com/satoren/kaguya/blob/15c09309edf15ddc3d51c1dc029093d5fbe7080e/test/benchmark_function.cpp#L68

**Comment by Unril** [comment]
Ok. Maybe also add some API to register c++ functions in a way to them be called without conversions and type checks? Now it's ~20x slower than self written lua_CFunction.

**Comment by satoren** [comment]
Not so much, if it is a simple function
kaguya_api_benchmark______::call_native_function average time:0.0695
original_api_no_type_check::call_native_function average time:0.056

But It has three slow cause
* userdata type check

  userdata type check is very slow now. include a member function call
* function overloads

  Bad case, type check is double per registered function.　double is weak and strict. and weak check in getting data on calling function.
* add property

  If using addProperty to metatable, add more field look up process. 
   * has not property

     return indextable[index]
   * has property

     if indextable['_prop_'..index] is exist call it, otherwise return indextable[index]  in metamethod


I want optimize userdata type check, but no idea now.

**Comment by Unril** [comment]
I mean something like `s["foo"].setFunctionWithoutChecks([](Test *t){});`. It sets overload number upvalue to -1 (for example). Invoker checks it and skips all type checks and conversions in release build. In that case user needs to be aware of what function signature he registeres. There are a small number of functions that require such approach. For example such that are called in loops.

**Comment by satoren** [comment]
It was not so fast

**Comment by satoren** [comment]
https://github.com/satoren/lua_binding_benchmark
Not so slow at current version.
