### ISSUE TITLE
CMake usage

### ISSUE THREAD

**Issue by Sahnvour** [satoren/kaguya#8]
I'm having trouble to build a solution for MSVC using your CMakeLists.txt.

I'm not used to CMake, is there a way I can specify where to find the Lua includes (and lib if necessary), for example using LuaJIT ? It seems your script assumes that the user has a standard Lua installation.

**Comment by satoren** [comment]
cmake -DLUA_INCLUDE_DIRS=path/to/lua/header/dir -DLUA_LIBRARY_DIRS=/abspath/to/lua/library/dir -DLUA_LIBRARIES=lualibname

e.g. my environment
download LuaJIT-2.0.4.zip 
unzip to kaguya dir
```
cd LuaJIT-2.0.4/src
./msvcbuild.bat
cd ../../
mkdir build
cd build
cmake ../ -DLUA_INCLUDE_DIRS=LuaJIT-2.0.4/src -DLUA_LIBRARY_DIRS=D:\MyDocument\GitHub\kaguya\LuaJIT-2.0.4\src -DLUA_LIBRARIES=lua51 -G "Visual Studio 14 2015 Win64"
```

**Comment by Sahnvour** [comment]
Thanks, it works (I had to compile LuaJIT in x64 to match kaguya).

**Comment by satoren** [comment]
loaded lua51.dll is correct?
Maybe that program loaded another dll. In that case you need  copy the DLL that you have compiled to working directory.

**Comment by Sahnvour** [comment]
Wow that was it, I'm so used to the pop up saying that X.dll is missing that I didn't even think of this.
Thanks again !

**Comment by district10** [comment]
I packed necessary Boost header files and Lua 5.3 with CMakeLists.txt, it works on Windows + Visual Studio 2010 without any extra dependency, hope this help: [4ker/kaguya at standalone](https://github.com/4ker/kaguya/tree/standalone).
